#!/usr/bin/env python3
"""build_pack.py: render the filming pack from the week file.

    python3 build_pack.py --week weeks/<date>.json [--dir <workspace>] [--out <path>]

The pack is what the creator reads to camera: the full spoken read (hook plus script), the
opinion slot that closes it, the shot list, the sources, and the LinkedIn text. Explainers add
the creator's own step-by-step guide; moments (day in the life, Pomodoro breaks) are a capture
list instead of a script. Until 3.11.0 it was prose a session typed
out, and prose typed once is regenerated by nobody: on 2026-09-21 a week file swapped two
episodes and the pack kept naming the old ones as the scripts to read. This renders it from
the record every time, so the two cannot disagree. `radar_gate.py` fails a pack older than
its week file.

Writes `<workspace>/show/<week>-filming-pack.md`. Exit 0 written, 2 on a missing file.
"""
import json
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.realpath(__file__)))
from yapcut_home import radar_home  # noqa: E402
import rules  # noqa: E402

HOME = radar_home()
DEFAULT_CEILING, DEFAULT_WPS = rules.get("script.word_ceiling"), rules.get("script.words_per_second")


def budget(home):
    try:
        cfg = json.load(open(os.path.join(home, "radar-config.json")))
        show = cfg.get("show") or {}
        return int(show.get("word_ceiling") or DEFAULT_CEILING), float(show.get("words_per_second") or DEFAULT_WPS)
    except (OSError, ValueError, TypeError):
        return DEFAULT_CEILING, DEFAULT_WPS


def load_cfg(home):
    try:
        return json.load(open(os.path.join(home, "radar-config.json")))
    except (OSError, ValueError):
        return {}


def opinion_lines(it, cfg):
    """The opinion slot (3.17.0): the script reports, the creator's own take closes it, said off
    the cuff. The ideas are prompts to riff on, never lines to read, and the slot is optional:
    with nothing to say, stop on the script's last line."""
    ideas = rules.opinion_ideas(it)
    if not ideas:
        return []
    return ([f"**{rules.opinion_label(cfg)}**", "",
             "_Off the cuff, your words. Take one of these, your own, or none and stop on the line above._"]
            + [f"- {i}" for i in ideas] + [""])


def words(*parts):
    return len(" ".join(p or "" for p in parts).split())


def shots(it):
    out = []
    for i, sh in enumerate(it.get("shot_list") or [], 1):
        if isinstance(sh, dict):
            n = sh.get("n") or i
            beat = str(sh.get("beat") or "")
            prefix = "" if re.match(r"^\d+\.", beat) else f"{n}. "
            line = f"{prefix}{beat}: {sh.get('shoot') or ''}"
            if sh.get("url"):
                line += f"\n   {sh['url']}"
            out.append(line.strip())
        else:
            out.append(f"{i}. {sh}")
    return out


def sources(it):
    out = []
    for s in it.get("sources") or []:
        if not isinstance(s, dict):
            continue
        label = s.get("label") or s.get("url") or ""
        pub = f", {s['published']}" if s.get("published") and s["published"] not in label else ""
        out.append(f"- {label}{pub}" + (f"\n  {s['url']}" if s.get("url") else ""))
    return out


def episode_block(it, wps, ceiling, cfg=None):
    n = words(it.get("spoken_hook"), it.get("script"))
    title = it.get("title") or it.get("id")
    ep = it.get("episode")
    company = it.get("company") or it.get("subject") or ""
    head = f"## Ep{ep}: {company}" if ep and company else f"## {title}"
    over = f"  OVER THE {ceiling} CEILING" if n > ceiling else ""
    lines = [head, "", f"_{title}_", "",
             f"_{n} words, about {n / wps:.0f} seconds.{over}_"]
    if it.get("text_hook"):
        lines.append(f"_On screen: {it['text_hook']}_")
    if it.get("story_line"):
        # The creator's gate (2026-10-05): the story in one line, what happened and why it
        # matters. It sits above the script so the read starts from the point, not the receipts.
        lines += ["", f"**The story in one line:** {it['story_line'].strip()}"]
    lines += ["", "**Open on (frame one, flat):**", f"> {(it.get('spoken_hook') or '').strip()}", "",
              (it.get("script") or "").strip(), ""]
    lines += opinion_lines(it, cfg)
    pb = it.get("pov_beat")
    if isinstance(pb, dict) and pb.get("beat"):
        lines += [f"_POV beat: {pb['beat']}_" + (f" _(source: {pb['source']})_" if pb.get("source") else ""), ""]
    if it.get("directions"):
        lines += ["**Directions:**", it["directions"].strip(), ""]
    sh = shots(it)
    if sh:
        lines += ["**Shots:**"] + sh + [""]
    src = sources(it)
    if src:
        lines += ["**Sources:**"] + src + [""]
    return "\n".join(lines)


def guide_lines(g):
    """An explainer's guide: the creator learns the thing before explaining it, so the pack
    carries the steps checked against the official docs, and how to say it to someone who has
    never done marketing."""
    if not isinstance(g, dict):
        return []
    out = ["### Your guide: learn it before you film it", ""]
    if g.get("what_it_is"):
        out += [f"**What it is:** {g['what_it_is']}", ""]
    if g.get("who_its_for"):
        out += [f"**Who it is for:** {g['who_its_for']}", ""]
    need = [n for n in g.get("you_need") or [] if n]
    if need:
        out += ["**You need:**"] + [f"- {n}" for n in need] + [""]
    steps = [st for st in g.get("steps") or [] if st]
    if steps:
        out.append("**Do it, step by step:**")
        for i, st in enumerate(steps, 1):
            if isinstance(st, dict):
                line = f"{i}. {st.get('do') or ''}"
                if st.get("why"):
                    line += f" _{st['why']}_"
                if st.get("url"):
                    line += f"\n   {st['url']}"
            else:
                line = f"{i}. {st}"
            out.append(line)
        out.append("")
    simply = [x for x in g.get("say_it_simply") or [] if x]
    if simply:
        out += ["**Say it simply (for someone who has never done marketing):**"] + [f"- {x}" for x in simply] + [""]
    if g.get("watch_out"):
        out += [f"**Watch out:** {g['watch_out']}", ""]
    if g.get("try_it_first"):
        out += [f"**Try it yourself before filming:** {g['try_it_first']}", ""]
    return out


def explainer_block(it, wps, cfg):
    n = words(it.get("spoken_hook"), it.get("script"))
    lo, hi = rules.get("explainer.target_seconds")
    secs = n / wps
    band = "" if lo <= secs <= hi else f"  OUTSIDE THE {lo} TO {hi} SECOND BAND"
    lines = [f"## Explainer: {it.get('title') or it.get('id')}", "",
             f"_{n} words, about {secs:.0f} seconds.{band}_"]
    if it.get("text_hook"):
        lines.append(f"_On screen: {it['text_hook']}_")
    g = it.get("guide") if isinstance(it.get("guide"), dict) else {}
    if g.get("who_its_for"):
        lines.append(f"_Explained for: {g['who_its_for']}_")
    lines += ["", "**Open on:**", f"> {(it.get('spoken_hook') or '').strip()}", "",
              (it.get("script") or "").strip(), ""]
    lines += opinion_lines(it, cfg)
    lines += guide_lines(g)
    if it.get("directions"):
        lines += ["**Directions:**", it["directions"].strip(), ""]
    sh = shots(it)
    if sh:
        lines += ["**Screens and shots:**"] + sh + [""]
    src = sources(it)
    if src:
        lines += ["**Sources:**"] + src + [""]
    return "\n".join(lines)


MOMENT_FORMATS = {"day-in-the-life": "Day in the life", "pomodoro-break": "Pomodoro break"}


def moment_block(it):
    """A moment is filmed, not read: a capture list for the day, cut later with time stamps."""
    fmt = MOMENT_FORMATS.get(it.get("format"), it.get("format") or "Moment")
    lines = [f"## {fmt}: {it.get('title') or it.get('id')}", ""]
    meta = []
    if it.get("film_on"):
        meta.append(f"film on {it['film_on']}")
    if it.get("length"):
        meta.append(f"cut to about {it['length']}")
    if meta:
        lines.append(f"_{', '.join(meta)}._")
    if it.get("text_hook"):
        lines.append(f"_On screen: {it['text_hook']}_")
    lines.append("")
    cap = [c for c in it.get("clips") or [] if c]
    if cap:
        lines += ["**Capture these (a few seconds each, phone in hand or propped):**", "",
                  "| Time | Moment | Shot |", "|---|---|---|"]
        for c in cap:
            if isinstance(c, dict):
                lines.append(f"| {c.get('t') or ''} | {c.get('moment') or ''} | {c.get('shot') or ''} |")
            else:
                lines.append(f"| | {c} | |")
        lines.append("")
    vo = [v for v in it.get("vo") or [] if v]
    if vo:
        lines += ["**Voiceover, optional (record after, over the picture):**"] + [f"- {v}" for v in vo] + [""]
    if it.get("edit"):
        lines += ["**Edit:**", str(it["edit"]).strip(), ""]
    return "\n".join(lines)


def post_block(post, parent=None):
    title = post.get("title") or (parent or {}).get("title") or post.get("id")
    lines = [f"### {title}", ""]
    if post.get("twin_cut"):
        lines.append(f"_twin cut this week: {post.get('cut_why') or 'no slot'}_")
        lines.append("")
        return "\n".join(lines)
    meta = []
    for k in ("job", "shape", "post_day"):
        if post.get(k):
            meta.append(f"{k} {post[k]}")
    if meta:
        lines += [f"_{', '.join(meta)}_", ""]
    lines += [(post.get("body") or "").strip(), ""]
    if post.get("reply_stance"):
        lines += [f"_Reply stance: {post['reply_stance']}_", ""]
    return "\n".join(lines)


def render(d, home):
    ceiling, wps = budget(home)
    cfg = load_cfg(home)
    week = d.get("week") or ""
    lane_of = lambda k: [it for it in d.get(k) or [] if isinstance(it, dict)]
    dist, office = lane_of("distribution"), lane_of("office")
    explainers, moments = lane_of("explainers"), lane_of("moments")
    lane = [p for p in d.get("linkedin") or [] if isinstance(p, dict)]
    eps = [it.get("episode") for it in dist if it.get("episode")]
    out = [f"# Filming pack, {week}", "",
           f"_Rendered by build_pack.py from weeks/{week}.json. Edit the week file, then re-render; "
           f"never edit this file by hand._", ""]
    extra = ""
    if explainers or moments:
        extra = f", {len(explainers)} explainer(s), {len(moments)} moment piece(s)"
    if eps:
        out.append(f"Ep{min(eps)} to Ep{max(eps)}, plus {len(office)} secondary-lane script(s){extra} "
                   f"and {len(lane)} standalone post(s).")
    else:
        out.append(f"{len(dist)} primary-lane script(s), {len(office)} secondary-lane script(s){extra}, "
                   f"{len(lane)} standalone post(s).")
    out += ["", "---", ""]
    for it in dist:
        out += [episode_block(it, wps, ceiling, cfg), "---", ""]
    for it in office:
        out += [episode_block(it, wps, ceiling, cfg), "---", ""]
    for it in explainers:
        out += [explainer_block(it, wps, cfg), "---", ""]
    for it in moments:
        out += [moment_block(it), "---", ""]
    twins = [(it.get("linkedin"), it) for it in dist if isinstance(it.get("linkedin"), dict)]
    if twins or lane:
        out += ["## LinkedIn", ""]
        for tw, parent in twins:
            out.append(post_block(tw, parent))
        for p in lane:
            out.append(post_block(p))
    return "\n".join(out).rstrip() + "\n"


def main():
    argv = sys.argv[1:]
    week = out_path = None
    i = 0
    while i < len(argv):
        if argv[i] == "--week" and i + 1 < len(argv):
            week = argv[i + 1]; i += 2
        elif argv[i] == "--out" and i + 1 < len(argv):
            out_path = argv[i + 1]; i += 2
        elif argv[i] in ("-h", "--help"):
            print(__doc__); return 0
        else:
            i += 1
    if not week:
        print(__doc__); return 2
    home = str(HOME)
    path = week if os.path.exists(week) or os.path.isabs(week) else os.path.join(home, week)
    if not os.path.exists(path):
        print(f"no week file at {path}"); return 2
    d = json.load(open(path))
    text = render(d, home)
    wk = (d.get("week") or os.path.basename(path)[:-5]).split()[0]
    dest = out_path or os.path.join(home, "show", f"{wk}-filming-pack.md")
    os.makedirs(os.path.dirname(dest), exist_ok=True)
    with open(dest, "w", encoding="utf-8") as fh:
        fh.write(text)
    print(f"wrote {dest} ({len(text.split())} words)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
